### PR TITLE
Updates infrastructure

### LINKED ISSUE #89: Use subprocess.Popen instead of subprocess.call
## Is your feature request related to a problem? Please describe.
There are a number of places where `update.py` calls external commands using `subprocess.call()`. If we used `subprocess.Popen` we'd have better control over the output of those commands.

## Describe the solution you'd like
Use `Popen` instead of `call` so that we can pipe the output of those commands to the right place.

### LINKED ISSUE #101: Add unit tests
## Is your feature request related to a problem? Please describe.
Right now it's hard to know whether or not the site will build without pulling it down and trying it. This is frustrating and makes it difficult for multiple people to contribute. 

## Describe the solution you'd like
Unit tests (and Travis CI integration) which ensure that code pushed to master will actually work.

### LINKED ISSUE #102: Update underlying infrastructure and versions of Python, Ruby and Jekyll
## Is your feature request related to a problem? Please describe.
The container for this app is currently based on CentOS 6, which is now two major versions behind the current version of CentOS. This means that the languages and dependencies installed in this OS (Python, Ruby, node.js, etc) are all VERY out of date, which requires a number of workarounds and hacky fixes.

## Describe the solution you'd like
Update the container to use a more recent version of CentOS. The application is currently deployed on a server running CentOS 7.5, so that's a good target.

### LINKED ISSUE #103: Improve deployment pattern for git submodules
## Is your feature request related to a problem? Please describe.
We currently version .gitmodules but we don't always want to deploy the same set of repositories (on dev, master, in a container)

## Describe the solution you'd like
1. Research options for deploying git submodules more flexibly.
2. Propose a path forward.

## Describe alternatives you've considered
It's also possible that git submodules are the wrong hammer for this nail. If that's the case, we'll need to find another solution.

### PR DESCRIPTION
**Pull request by helrond**
Updates a number of pieces of underlying infrastructure:
- Uses CentOS 8.2, fixes #102
- Uses Ruby 2.6.6, fixes #102
- Serves both public and private sites using Apache rather than Node server
- Adds a `.travis.yml` file and refactors `entrypoint.sh` so that Travis will build sites on push, fixes #101
- Improves behavior of `update.py`, fixes #89 
- Improved handling of git submodules, fixes #103 

This shouldn't be merged until we've confirmed an upgrade path for the existing servers.

### CODE REVIEW

**Comment by helrond** [comment]
@daremiyo @kemartin2015 @HaSistrunk I've asked for your review on this to make sure I'm not missing something which will prevent folks from pulling down this repository and standing it up. When you have the time, if you'd be willing to pull down this branch, build and see if you can get it to work as described in the README that would really appreciated!

**Review by kemartin2015 — APPROVED** [review]
@helrond, I was able to pull down the changes, run the docker-compose up command, and it built the site locally as described in the README.

**Review by daremiyo — APPROVED** [review]
worked for me!

**Comment by HaSistrunk** [comment]
@helrond when I do `docker-compose up`, it's hanging up on:

**Comment by kemartin2015** [comment]
@helrond, looking at this again, I pulled the changes to the wrong branch the first time, and now after pulling changes to the correct branch I'm also getting hung up in the same place as @HaSistrunk.

**Comment by helrond** [comment]
@HaSistrunk @kemartin2015 I think that's actually expected behavior. Are you able to access the sites at `localhost:4000` and `localhost:4001`?

**Comment by HaSistrunk** [comment]
Yeah, I can access the site at both. Ok - threw me off as I was waiting for it to "finish".

**Review by HaSistrunk — APPROVED** [review]

**Comment by helrond** [comment]
@HaSistrunk OK, so maybe I need to echo something out of `entrypoint.sh` so users know the site is there? I can also take care of that Apache warning.

**Comment by kemartin2015** [comment]
@helrond that would be helpful. thanks!

**Comment by HaSistrunk** [comment]
Yeah, if that's simple enough I think it would be nice.

**Comment by helrond** [comment]
Great, thanks for your help, all!

**Pull request merged**
